import { Account, Category, Transaction, CheckItem, DebtItem, LoanItem, SavingGoal, FamilyMember, FamilyAllowanceRequest } from '../types';
import { getTodayISO, getTodayJalali, formatToJalali } from './jalali';

export const INITIAL_FAMILY_MEMBERS: FamilyMember[] = [
  {
    id: 'head',
    name: 'مسعود مژده‌ور (سرپرست)',
    role: 'head',
    avatar: '👨‍💼',
    color: 'blue',
    assignedAccountIds: [], // All accounts
    monthlyAllowance: 25000000,
    isActive: true,
    createdAt: '2026-01-01',
    phone: '09123456789',
    notes: 'سرپرست و مدیر ارشد مالی خانواده',
  },
  {
    id: 'mem-spouse',
    name: 'مریم (همسر)',
    role: 'spouse',
    avatar: '👩',
    color: 'rose',
    assignedAccountIds: ['acc-blu', 'acc-cash'],
    monthlyAllowance: 12000000,
    pin: '1234',
    isActive: true,
    createdAt: '2026-01-02',
    phone: '09129876543',
    notes: 'مدیریت خریدهای خانه و سوپرمارکت',
  },
  {
    id: 'mem-child1',
    name: 'سارا (فرزند)',
    role: 'child',
    avatar: '👧',
    color: 'purple',
    assignedAccountIds: ['acc-blu'],
    monthlyAllowance: 3500000,
    pin: '2026',
    isActive: true,
    createdAt: '2026-01-05',
    phone: '09351112233',
    notes: 'دانشجو - هزینه‌های دانشگاه، کتاب و رفت‌وآمد',
  },
  {
    id: 'mem-child2',
    name: 'امیرعلی (فرزند)',
    role: 'child',
    avatar: '👦',
    color: 'emerald',
    assignedAccountIds: ['acc-cash', 'acc-blu'],
    monthlyAllowance: 2000000,
    pin: '1111',
    isActive: true,
    createdAt: '2026-01-10',
    notes: 'دانش‌آموز - پول توجیبی مدرسه و کلاس زبان',
  },
];

export const INITIAL_ALLOWANCE_REQUESTS: FamilyAllowanceRequest[] = [
  {
    id: 'req-1',
    memberId: 'mem-child1',
    memberName: 'سارا (فرزند)',
    memberAvatar: '👧',
    amount: 450000,
    reason: 'خرید کتاب‌های تخصصی دانشگاه و جزوه',
    date: '2026-08-25',
    jalaliDate: '1405/06/03',
    status: 'pending',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  // Expense Categories
  { id: 'cat-food', name: 'خوراک و سوپرمارکت', nameEn: 'Food & Groceries', type: 'expense', icon: 'Utensils', color: '#f59e0b', budgetMonthly: 12000000 },
  { id: 'cat-housing', name: 'مسکن و قبوض', nameEn: 'Housing & Utilities', type: 'expense', icon: 'Home', color: '#ef4444', budgetMonthly: 25000000 },
  { id: 'cat-transport', name: 'حمل‌ونقل و بنزین', nameEn: 'Transportation', type: 'expense', icon: 'Car', color: '#3b82f6', budgetMonthly: 4500000 },
  { id: 'cat-health', name: 'سلامت و درمان', nameEn: 'Health & Medical', type: 'expense', icon: 'Activity', color: '#ec4899', budgetMonthly: 3000000 },
  { id: 'cat-entertainment', name: 'سرگرمی و کافه', nameEn: 'Entertainment & Cafe', type: 'expense', icon: 'Film', color: '#8b5cf6', budgetMonthly: 3500000 },
  { id: 'cat-shopping', name: 'خرید و پوشاک', nameEn: 'Shopping & Clothes', type: 'expense', icon: 'ShoppingBag', color: '#10b981', budgetMonthly: 6000000 },
  { id: 'cat-education', name: 'آموزش و کتاب', nameEn: 'Education', type: 'expense', icon: 'GraduationCap', color: '#06b6d4', budgetMonthly: 2000000 },
  { id: 'cat-installment', name: 'اقساط و بدهی', nameEn: 'Loans & Debts', type: 'expense', icon: 'CreditCard', color: '#f97316', budgetMonthly: 8500000 },
  { id: 'cat-other-exp', name: 'سایر مخارج', nameEn: 'Other Expenses', type: 'expense', icon: 'MoreHorizontal', color: '#64748b', budgetMonthly: 2000000 },

  // Income Categories
  { id: 'cat-salary', name: 'حقوق و دستمزد', nameEn: 'Salary & Wage', type: 'income', icon: 'Briefcase', color: '#10b981' },
  { id: 'cat-freelance', name: 'پروژه و فریلنسری', nameEn: 'Freelance & Projects', type: 'income', icon: 'Laptop', color: '#3b82f6' },
  { id: 'cat-investment', name: 'سود بانکی و سرمایه', nameEn: 'Investment Returns', type: 'income', icon: 'TrendingUp', color: '#8b5cf6' },
  { id: 'cat-gift', name: 'هدیه و پاداش', nameEn: 'Gift & Bonus', type: 'income', icon: 'Gift', color: '#f59e0b' },
  { id: 'cat-other-inc', name: 'سایر درآمدها', nameEn: 'Other Incomes', type: 'income', icon: 'PlusCircle', color: '#14b8a6' },
];

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc-blu',
    name: 'بلو بانک (سامان)',
    bankName: 'بانک سامان (Blu)',
    type: 'bank',
    cardNumber: '6219861054321289',
    balance: 48500000,
    color: 'from-blue-600 to-indigo-800',
    isDefault: true,
  },
  {
    id: 'acc-mellat',
    name: 'حساب اصلی ملت',
    bankName: 'بانک ملت',
    type: 'bank',
    cardNumber: '6104337890123456',
    balance: 112000000,
    color: 'from-rose-600 to-red-900',
  },
  {
    id: 'acc-cash',
    name: 'کیف پول نقدی و جاری',
    bankName: 'نقدی',
    type: 'cash',
    balance: 4200000,
    color: 'from-emerald-600 to-teal-800',
  },
  {
    id: 'acc-gold',
    name: 'صندوق طلا و سکه',
    bankName: 'طلای ۱۸ عیار و سکه',
    type: 'gold',
    balance: 245000000,
    color: 'from-amber-500 to-yellow-700',
  },
  {
    id: 'acc-crypto',
    name: 'کیف پول تتر / کریپتو',
    bankName: 'Tether & Crypto',
    type: 'crypto',
    balance: 86000000,
    color: 'from-violet-600 to-purple-900',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    type: 'income',
    amount: 45000000,
    categoryId: 'cat-salary',
    accountId: 'acc-mellat',
    date: '2026-08-20',
    jalaliDate: '1405/05/29',
    description: 'واریز حقوق ماهانه شرکت',
    memberId: 'head',
    memberName: 'مسعود (سرپرست)',
    memberRole: 'head',
  },
  {
    id: 'tx-2',
    type: 'expense',
    amount: 3800000,
    categoryId: 'cat-food',
    accountId: 'acc-blu',
    date: '2026-08-22',
    jalaliDate: '1405/05/31',
    description: 'خرید هفتگی سوپرمارکت و میوه',
    memberId: 'mem-spouse',
    memberName: 'مریم (همسر)',
    memberRole: 'spouse',
  },
  {
    id: 'tx-3',
    type: 'expense',
    amount: 1450000,
    categoryId: 'cat-transport',
    accountId: 'acc-blu',
    date: '2026-08-23',
    jalaliDate: '1405/06/01',
    description: 'بنزین و اسنپ رفت‌وآمد دانشگاه',
    memberId: 'mem-child1',
    memberName: 'سارا (فرزند)',
    memberRole: 'child',
  },
  {
    id: 'tx-4',
    type: 'income',
    amount: 18000000,
    categoryId: 'cat-freelance',
    accountId: 'acc-blu',
    date: '2026-08-24',
    jalaliDate: '1405/06/02',
    description: 'تسویه فاز اول پروژه طراحی وب',
    memberId: 'head',
    memberName: 'مسعود (سرپرست)',
    memberRole: 'head',
  },
  {
    id: 'tx-5',
    type: 'expense',
    amount: 8500000,
    categoryId: 'cat-installment',
    accountId: 'acc-mellat',
    date: '2026-08-25',
    jalaliDate: '1405/06/03',
    description: 'پرداخت قسط وام خرید کالا',
    memberId: 'head',
    memberName: 'مسعود (سرپرست)',
    memberRole: 'head',
  },
  {
    id: 'tx-6',
    type: 'expense',
    amount: 850000,
    categoryId: 'cat-education',
    accountId: 'acc-blu',
    date: '2026-08-26',
    jalaliDate: '1405/06/04',
    description: 'خرید کتاب زبان و جزوه دانشگاهی',
    memberId: 'mem-child1',
    memberName: 'سارا (فرزند)',
    memberRole: 'child',
  },
  {
    id: 'tx-7',
    type: 'expense',
    amount: 620000,
    categoryId: 'cat-entertainment',
    accountId: 'acc-cash',
    date: '2026-08-27',
    jalaliDate: '1405/06/05',
    description: 'کلاس ورزشی و تنقلات مدرسه',
    memberId: 'mem-child2',
    memberName: 'امیرعلی (فرزند)',
    memberRole: 'child',
  },
  {
    id: 'tx-8',
    type: 'expense',
    amount: 2400000,
    categoryId: 'cat-shopping',
    accountId: 'acc-blu',
    date: '2026-08-28',
    jalaliDate: '1405/06/06',
    description: 'خرید لباس و وسایل منزل',
    memberId: 'mem-spouse',
    memberName: 'مریم (همسر)',
    memberRole: 'spouse',
  },
];

export const INITIAL_CHECKS: CheckItem[] = [
  {
    id: 'chk-1',
    type: 'issued',
    checkNumber: '44892100',
    sayadId: '14039827361928',
    bankName: 'بانک ملت',
    amount: 32000000,
    recipientOrPayer: 'آقای رضایی (خرید تجهیزات)',
    dueDate: '2026-09-05',
    dueJalaliDate: '1405/06/14',
    status: 'pending',
    accountId: 'acc-mellat',
    notes: 'بابت تسویه فاکتور خرید سخت‌افزار',
  },
  {
    id: 'chk-2',
    type: 'received',
    checkNumber: '78239012',
    sayadId: '98472910384721',
    bankName: 'بانک پاسارگاد',
    amount: 45000000,
    recipientOrPayer: 'شرکت پویندگان (پروژه نرم‌افزار)',
    dueDate: '2026-09-15',
    dueJalaliDate: '1405/06/24',
    status: 'pending',
    accountId: 'acc-blu',
    notes: 'چک صیادی بابت قرارداد سالانه',
  },
];

export const INITIAL_DEBTS: DebtItem[] = [
  {
    id: 'dbt-1',
    type: 'receivable',
    personName: 'علی محمدی',
    phone: '09123456789',
    totalAmount: 15000000,
    paidAmount: 5000000,
    dueDate: '2026-09-20',
    dueJalaliDate: '1405/06/29',
    isSettled: false,
    notes: 'قرض‌الحسنه جهت خرید موتور',
    createdAt: '2026-08-01',
  },
  {
    id: 'dbt-2',
    type: 'debt',
    personName: 'حسین احمدی (قرض)',
    phone: '09351234567',
    totalAmount: 10000000,
    paidAmount: 0,
    dueDate: '2026-09-10',
    dueJalaliDate: '1405/06/19',
    isSettled: false,
    notes: 'بدهی بابت خرید قطعات لپ‌تاپ',
    createdAt: '2026-08-15',
  },
];

export const INITIAL_LOANS: LoanItem[] = [
  {
    id: 'loan-1',
    title: 'وام خرید مسکن / کالا',
    bankName: 'بانک ملت',
    principalAmount: 100000000,
    totalAmount: 144000000,
    interestRate: 23,
    totalInstallments: 24,
    paidInstallments: 7,
    monthlyPayment: 6000000,
    startDate: '2026-01-10',
    startJalaliDate: '1404/10/20',
    dueDayOfMonth: 20,
    accountId: 'acc-mellat',
  },
  {
    id: 'loan-2',
    title: 'وام ازدواج / قرض‌الحسنه',
    bankName: 'بانک رسالت',
    principalAmount: 60000000,
    totalAmount: 62400000,
    interestRate: 4,
    totalInstallments: 36,
    paidInstallments: 14,
    monthlyPayment: 1730000,
    startDate: '2025-06-05',
    startJalaliDate: '1404/03/15',
    dueDayOfMonth: 15,
    accountId: 'acc-blu',
  },
];

export const INITIAL_GOALS: SavingGoal[] = [
  {
    id: 'goal-1',
    title: 'خرید خودرو جدید',
    targetAmount: 500000000,
    currentAmount: 285000000,
    targetDate: '2027-03-20',
    targetJalaliDate: '1405/12/29',
    category: 'خودرو',
    color: '#3b82f6',
    icon: 'Car',
    notes: 'پس‌انداز ماهانه در صندوق طلا و سپرده',
  },
  {
    id: 'goal-2',
    title: 'صندوق پس‌انداز اضطراری',
    targetAmount: 120000000,
    currentAmount: 95000000,
    targetDate: '2026-12-30',
    targetJalaliDate: '1405/10/09',
    category: 'اضطراری',
    color: '#10b981',
    icon: 'ShieldCheck',
    notes: 'پوشش مخارج ۶ ماه زندگی',
  },
  {
    id: 'goal-3',
    title: 'سفر تفریحی تعطیلات نوروز',
    targetAmount: 60000000,
    currentAmount: 34000000,
    targetDate: '2027-03-15',
    targetJalaliDate: '1405/12/24',
    category: 'سفر',
    color: '#f59e0b',
    icon: 'Plane',
    notes: 'بلیط و اقامت',
  },
];
